### ISSUE TITLE
Can't login to events.opensuse.org

### ISSUE THREAD

**Issue by dguttierrez** [openSUSE/osem#2375] opened 2019-02-27 09:54 UTC
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

When I login to https://events.opensuse.org/conferences/oSC19 I got Error 500: Internal error.

**Expected correct behavior:**

There must be registration portal.

**Steps to reproduce:**

It happened to my username only "ast53". Coworker testet with his user/pass and have no errors. I have try to change password, but error is still there. I can Login to MicroFocus site.

**Other information:**

**Comment by Ana06** [comment] 2019-02-28 16:41
@hennevogel is that the problem which generate several users with same logins and different emails? Do we have an idea of how we want to solve this?

**Comment by hennevogel** [comment] 2019-02-28 22:52
> is that the problem which generate several users with same logins and different emails?

Yeah there are two users in the production DB

a = {email: 'blah@example.com', username: 'user123', created_at: 2014-12-20)
b = {email: 'some@where.com, username: 'somewhere', created_at: 2013-02-28}

Now @dguttierrez tries to log in with 'somewhere' which in turn tries to update the email of that user to 'blah@example.com' because this is what the login proxy tells us (what is configured in the SUSE account) . But we can't have two users with the same email as we have a unique index on this.
I have no idea how that is possible that inside the SUSE login service a user can create an account with an already existing email. AFAIU it can't happen, but it happens. This is not the first time I see this.

As temporary fix I have merged users manually. You should be able to log in now @dguttierrez

**Comment by dguttierrez** [comment] 2019-03-01 06:38
Hello

I confirm, that registration now works.

Regards, Davor

**Comment by Ana06** [comment] 2019-03-01 09:45
@hennevogel but we can not know what users are affected until they report it, or do we have a way to know that? :thinking:

**Comment by hennevogel** [comment] 2019-03-01 16:21
nope. and you also never know the direction (which one of the two logins they use) until it happens. We could get rid of the index so we can have multiple accounts with the same email. But I'm not sure we're prepared for this.

**Comment by age-killer** [comment] 2019-05-20 14:33
Hello,

I am trying to register to oSC19, but I constantly get a "Redirection limit for this URL exceeded. Unable to load the requested page. This may be caused by cookies that are blocked." error, on both my PC and phone (4G network) with several browsers. This happens when I submit my credentials.

Is there a general issue with the page or I have duplicate accounts as well?

Thanks a lot for the help,
Anatoli

**Comment by hennevogel** [comment] 2019-05-20 14:45
What is your user name @age-killer?

**Comment by age-killer** [comment] 2019-05-20 14:51
> 
> 
> What is your user name @age-killer?

should be AGE_KILLER

**Comment by hennevogel** [comment] 2019-05-21 09:11
> should be AGE_KILLER

it is not...

**Comment by Ana06** [comment] 2019-05-21 21:17
I think it is `archimed` :wink:

**Comment by age-killer** [comment] 2019-05-22 06:50
> I think it is `archimed` 😉

Okay... so it seems that there is either a mess with SUSE and openSUSE accounts or I do have two accounts with different access and the "reset all" functionality is not working for me... Anyways, I created a new account and registered for the conference :D Whom should I contact to delete all my other accounts?

Thank you very much for the quick responses!

Kind regards,
Anatoli

**Comment by Ana06** [comment] 2019-05-22 08:54
@hennevogel 

> As temporary fix I have merged users manually. You should be able to log in now @dguttierrez

how have you done this? have you written an script to update the index of the deleted user to the other one. If so, it would be nice to share the script :wink:

**Comment by Ana06** [comment] 2019-05-22 10:12
@age-killer 

> Okay... so it seems that there is either a mess with SUSE and openSUSE accounts or I do have two accounts with different access and the "reset all" functionality is not working for me... Anyways, I created a new account and registered for the conference :D Whom should I contact to delete all my other accounts?

There is not "reset functionality", just us merging users manually, which we haven't done for your accounts. Your account doesn't seem to be affected by the same issue. There is no user `age_killer` and only one account for `archimed` and the email for this user is not in any other user.

What user where you trying to log in with? can you provide more details of how to reproduce the error?

**Comment by age-killer** [comment] 2019-05-22 11:25
> @age-killer
> 
> > Okay... so it seems that there is either a mess with SUSE and openSUSE accounts or I do have two accounts with different access and the "reset all" functionality is not working for me... Anyways, I created a new account and registered for the conference :D Whom should I contact to delete all my other accounts?
> 
> There is not "reset functionality", just us merging users manually, which we haven't done for your accounts. Your account doesn't seem to be affected by the same issue. There is no user `age_killer` and only one account for `archimed` and the email for this user is not in any other user.
> 
> What user where you trying to log in with? can you provide more details of how to reproduce the error?

I meant the "Retrieve both" option in the "Forgot your credentials?" section of the Sign in page, but didn't receive anything... I have an AGE_KILLER account, but this might be related only to SUSE, which would explain why I cannot login to openSUSE's Event page. As for the archimed account... I suspect that this might be one of the first accounts I have created couple of years ago for accessing the forum or when I registered for the conference back in 2013 :$ Either way, I have lost all information about the archimed account :D

**Comment by Ana06** [comment] 2019-05-22 11:32
@age-killer 

> I meant the "Retrieve both" option in the "Forgot your credentials?" section of the Sign in page, but didn't receive anything... I have an AGE_KILLER account, but this might be related only to SUSE, which would explain why I cannot login to openSUSE's Event page. As for the archimed account... I suspect that this might be one of the first accounts I have created couple of years ago for accessing the forum or when I registered for the conference back in 2013 :$ Either way, I have lost all information about the archimed account :D

There is not `AGE_KILLER` account in OSEM. The `Retrieve both` option is on the microfocus page and not in OSEM. So I think there is nothing we can do about it, right @hennevogel?

**Comment by age-killer** [comment] 2019-05-22 11:40
> @age-killer
> 
> > I meant the "Retrieve both" option in the "Forgot your credentials?" section of the Sign in page, but didn't receive anything... I have an AGE_KILLER account, but this might be related only to SUSE, which would explain why I cannot login to openSUSE's Event page. As for the archimed account... I suspect that this might be one of the first accounts I have created couple of years ago for accessing the forum or when I registered for the conference back in 2013 :$ Either way, I have lost all information about the archimed account :D
> 
> There is not `AGE_KILLER` account in OSEM. The `Retrieve both` option is on the microfocus page and not in OSEM. So I think there is nothing we can do about it, right @hennevogel?

I knew there is something messy with all these reorganizations SUSE is going through lately... Apologies for spamming the thread and thanks a lot for your time and patience!

**Closed** 2019-05-24 07:52 UTC
Labels: bug :bug:, production
