### ISSUE TITLE
Error 500: Internal Server Error when adding this character to biography 🐘

### ISSUE THREAD

**Issue by AlicjaKucharczyk** [openSUSE/osem#3258] opened 2023-10-18 18:17 UTC
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Getting Error 500: Internal Server Error when adding this character to biography 🐘 in Edit your profile page

**Expected correct behavior:**
no error :)

**Steps to reproduce:**
go to Edit your profile and try to use 🐘 somewhere

**Other information:**

**Comment by AndrewKvalheim** [comment] 2023-10-18 23:10
Sounds like #2686

**Comment by hennevogel** [comment] 2023-11-02 16:05
duplicate of #2686

**Closed as completed by hennevogel** 2023-11-02 16:05 UTC
