### ISSUE TITLE
How do you ACTUALLY install this?

### ISSUE THREAD

**Issue by grepwood** [openSUSE/osem#2065] opened 2018-06-04 23:18 UTC
I read `INSTALL.md` and I'm just left scratching my head.

**Comment by grepwood** [comment] 2018-06-06 13:39
Current INSTALL.md is completely useless. The one from https://github.com/openSUSE/osem/tree/73c15e940458daf7da59ed855a987a4d2cc2123c is a lot better.

**Comment by andlrb** [comment] 2018-06-10 19:54
Hi @grepwood!
You have not mentioned if you're trying to install OSEM in a production or development environment. The installation guide you've shared is 4 years old, so it's a bit outdated in regards to how you need to run it in development but it's the same when running in production (with mod_passenger and apache web-server). If you're looking to run OSEM in development and contribute to the repository, then please have a look at [CONTRIBUTING.md](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).

**Comment by differentreality** [comment] 2018-06-24 16:08
@grepwood the current INSTALL file provisions for the option to use docker for your installation, instead of a manual installation. Is it safe to assume you don't want that?
You also have the option to run OSEM on Heroku.

If you do want to have a manual installation, then yes, indeed, you would have to go through the usual suspects in Rails applications. 

Please also note that we are now using .env file for all variables that need to be set.

I would hope that by now you have your installation up and running. If not, feel free to reach out.

**Comment by grepwood** [comment] 2018-06-28 11:56
@differentreality yes, I wanted to have a manual install, much like I used to deploy Play and Wordpress at work. The old documentation is more than helpful for that end. It's really great and I can deploy OSEM behind Apache/nginx, hook it up to a PostgreSQL cluster or a replicated MariaDB, run Grafana and Sensu alongside to do more in-detail telemetry... it's absolutely great and I'd like to even contribute OpenRC and systemd service files for OSEM that I've been developing for my personal convenience.

**Comment by MysterAitch** [comment] 2018-07-02 05:17
To add to this, as somebody brand new to the project (came over via a PyPi recommendation on the FLOSS Weekly podcast), it is unclear where/how to obtain the "latest" version for installation. 

_Note that the releases page on GitHub (linked to from the installation documentation) includes only v1.0 dated May 24, 2016. This is reported as being over two years and 1156 commits ago._ 

Is it fair to say that installation using Docker and Heroku are the only supported installation methods at the moment? As somebody unfamiliar with the use of Docker/Heroku I do not know how to check the "latest" version available via there - is that version kept more up-to-date than the releases page? How about the master branch - is it kept in a stable state that can be downloaded and installed/run?

**Comment by differentreality** [comment] 2018-07-02 07:52
Hi @MysterAitch, indeed it is on our todo list to have a more recent release. Until that happens, you could use our master branch, which is continuously updated and indeed includes a lot of changes, and new features.

Which way would you like to use to install OSEM? 
If you merely want to check it out, you can also use demo.osem.io

**Comment by MysterAitch** [comment] 2018-07-04 17:58
Hi @differentreality , 

Thank you for confirming that the master branch is kept in a stable state that can be installed/run.

I am looking to use OSEM to plan a multi-stream training event, specifically making use of the scheduling and timetabling elements of OSEM to replace various spreadsheets that are currently used (no need for the abstract/submission processes for this event but may suggest it for a local academic conference). Happy to go into more detail but don't wish to hijack this issue. A hosted version would be ideal, but I understand that this is not currently available. 

A local virtual machine (ideally setup using vagrant - docker not available here) seems to be the way forward for now as a means of trying to figure out how much OSEM is able to do without investing too much effort into uploading data to the demo site. Depending on how well it works locally (the demo site is very promising!) then I am certainly open to transferring/installing it to a publicly accessible server (perhaps Heroku?) to share with the rest of the team and potentially run registration/payment components but I'll need to explore further before running with that. 

Sidenote - this issue appears to be a duplicate of https://github.com/openSUSE/osem/issues/1975 ?

**Comment by differentreality** [comment] 2018-07-05 05:43
Heroku makes a lot of sense.

A hosted OSEM is not yet available, no.

And yes, indeed, #1975 is about the same thing. Thanks!

Feel free to reach out if you have any questions about using OSEM!

**Comment by Ana06** [comment] 2018-08-02 21:47
Isn't this issue just a duplicated of https://github.com/openSUSE/osem/issues/1975? I know this was was open before, but I found the explanation in the other clearer, as we have installation instructions, just only for docker. Should we close this? :thinking:

**Comment by aspiers** [comment] 2019-01-11 10:20
The current `INSTALL.md` in `master` is indeed out of date, for example it refers to files which no longer exist.  I would suggest that fixing this should be one of the highest priority tasks for the project, since if the documented installation process doesn't work then that will quickly scare away any potential contributors (including me).

**Comment by aspiers** [comment] 2019-01-11 12:36
Thanks for the quick replies!

[**@differentreality**](https://github.com/differentreality) commented on [11 Jan 2019, 11:27 GMT](https://github.com/openSUSE/osem/issues/2065#issuecomment-453488277 "2019-01-11T11:27:18Z - Replied by Github Reply Comments"):
> @aspiers which files in particular have you noticed missing but yet mentioned in https://github.com/openSUSE/osem/blob/master/INSTALL.md?

Most of the files mentioned in the "Deploy with Docker" section. `docker-compose.yml.example` doesn't exist, and even if it did, copying it to `docker-compose.yml` doesn't make sense because the latter already exists.  There are also no `docker-compose.env*` files.  

> Henne's reply is relevant to this: https://github.com/openSUSE/osem/issues/1975#issuecomment-410188367
> 
> We want to encourage people to know what they are doing when setting up OSEM (or anything else for that matter) in production (or ask help from someone who knows).

I'd say that a very good way to encourage people to know what they are doing is to help them learn ;-)  And documentation is the cheapest way to achieve this.  Of course it doesn't make sense to duplicate docs on things like Rails, Passenger etc. so in those cases it should be good enough to provide links to the official docs.

OTOH I totally understand the concern about not wanting to burn giving free consultancy / training to Rails/Docker newbies.  But that can be addressed simply by clearly setting expectations around levels of support.  IMHO it's not a good reason not to document stuff, since it's still possible to say "here's documentation for this installation route, but we can only offer best-effort support, so if you aren't an expert with $DEPLOYMENT_TECHNOLOGY then you may need to pay a consultant to help you."

Of course you can also say "OTOH if you are an expert then please help us make the docs better!"

> As far as development is concerned, to run a Rails application, without docker, you need:

Ah thanks, but I want to use docker :-)

**Comment by hennevogel** [comment] 2019-01-11 12:46
> Most of the files mentioned in the "Deploy with Docker" section

That's my fault as I have changed our docker setup. I'll address this...

**Comment by grepwood** [comment] 2019-01-16 17:27
Me and my customer moved to a proprietary solution as time was of the essence and we couldn't focus on OSEM. For what it's worth, I'm still interested on providing an installation manual for setups outside of Docker in the last week of January. This week all of my efforts are pre-allocated to my paid duties.

**Closed** 2019-02-01 00:00 UTC
Labels: Documentation

**Comment by Ana06** [comment] 2019-02-01 10:55
@grepwood 

> Me and my customer moved to a proprietary solution as time was of the essence and we couldn't focus on OSEM. For what it's worth, I'm still interested in providing an installation manual for setups outside of Docker in the last week of January, as this is useful knowledge. It would be disrespectful of other people's time to waste it on figuring this out themselves. This week all of my efforts are pre-allocated to my paid duties.

PRs are always welcome. If you think the documentation can be improved, we will be more than happy to review your improvement suggestions.
