### ISSUE TITLE
SQL Exception 

### ISSUE THREAD

**Issue by chashmeetsingh** [openSUSE/osem#814] opened 2016-03-03 16:21 UTC
```
rake db:migrate
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: roles: SELECT "roles".* FROM "roles"
```

I cloned the master branch of the repo

**Comment by ChrisBr** [comment] 2016-03-03 16:22
did you run the migrations? Do you use vagrant?

**Comment by chashmeetsingh** [comment] 2016-03-03 16:24
rake db:migrate is for running migrations right?
no I don't use vagrant @ChrisBr

**Comment by ChrisBr** [comment] 2016-03-03 16:27
Yes, right!
http://edgeguides.rubyonrails.org/active_record_migrations.html

Try running: 

``
bundle exec rake db:setup
``

**Comment by chashmeetsingh** [comment] 2016-03-03 16:43
@ChrisBr 
bundle exec rake db:setup
db/development.sqlite3 already exists
db/test.sqlite3 already exists
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: roles: SELECT "roles".* FROM "roles"

**Comment by ChrisBr** [comment] 2016-03-03 16:44
remove the database first db/development.sqlite3

**Comment by chashmeetsingh** [comment] 2016-03-03 16:47
still the same issue

bundle exec rake db:setup
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: roles: SELECT "roles".* FROM "roles"

**Comment by chashmeetsingh** [comment] 2016-03-03 16:48
There is some problem with the timestamp of the migration file 
For it to work I have to manually create the table :(

**Comment by ChrisBr** [comment] 2016-03-03 16:57
@chashmeetsingh please provide some more details / stacktrace! I'm not able to reproduce...

**Comment by chashmeetsingh** [comment] 2016-03-03 16:59
- I cloned the master branch 
- ran bundle update
- then ran rake db:setup 

Then I get this error

**Comment by ChrisBr** [comment] 2016-03-04 07:38
What do you mean with 

> There is some problem with the timestamp of the migration file

**Comment by hennevogel** [comment] 2016-03-04 12:11
`bundle update` is updating your bundle to the latest gem versions. You want to

```
git checkout Gemfile*
bundle install
rake db:drop db:setup
```

No need for running the migrations when you're setting up a fresh database

**Comment by chashmeetsingh** [comment] 2016-03-04 13:24
`rake db:drop db:setup
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: roles: SELECT "roles".* FROM "roles"
`

**Comment by ChrisBr** [comment] 2016-03-05 14:21
@chashmeetsingh do you use Vagrant?
We had some issues with our vagrant bootstrap file, but #832 and #823 should fix these issues. I also had some weird migration issues and the reason was that the bootstrap file didn't create a config.yml. Do you have a config.yml in you config folder?

As soon as #832 is merged, can you try to setup it with vagrant?

**Comment by awasum** [comment] 2016-03-07 05:29
hello everyone,
Am awasum from buea, cameroon.
I assume @chashmeetsingh problem is setting up the OSEM development environment without vagrant??
I did mine as follows:

- install ruby 2.2 and rails 4.2 on ubuntu 14.04

- clone osem into my home directory: `git clone https://github.com/openSUSE/osem.git`

- cd into your osem folder and run `bundle install`, make sure all gems are installed.

- Get into your osem/config directory and rename config.yml.example, database.yml.example, piwik.yml.example into config.yml , database.yml , piwik.yml respectively.

- run `rake secret` on the terminal and add the secret key in `/home/username/osem/config/initializers/devise.rb` as such
`config.secret_key = '0014809cd45aa9fc57a29118bbbc374437095fed0b39549b69aef61b9ad994f0e71a0bf54e66a5acec3d67d293495c1b6f4235e8b6415e4fe2bafb8f517121ea'
`
- still in your osem directory, run `rake db:setup` then `rake db:migrate`

- run `rails server`

- visit localhost:3000 with your browser

**Comment by differentreality** [comment] 2016-03-10 19:06
Is there still some issue with this? If not, please close it.

**Closed** 2016-03-10 19:13 UTC

**Comment by Rolence** [comment] 2016-03-14 14:37
its okay now but i didn't use vagrant to setup my developer's environtment
