### ISSUE TITLE
Confirmed user and attendance toggles are broken #2472

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/osem#2484] opened 2019-04-05 14:13 UTC
With the update, there is no longer an ability to check off attendees as present. In the previous version, there was an option to record attendees as present and generate a dashboard with information about the amount of people who attended an event.
![registration attendee](https://user-images.githubusercontent.com/8996626/55633859-89921b00-57bd-11e9-9485-89fccabf0917.png)

**Comment by Ana06** [comment] 2019-05-24 22:42
This seems to be a duplicate of https://github.com/openSUSE/osem/issues/2472

**Closed by Ana06** 2019-05-24 22:42 UTC
Labels: P1, Regression, bug :bug:, production
