### ISSUE TITLE
horizontal schedule confusing and buggy

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osem#2460] opened 2019-03-26 10:21 UTC
Looking at https://events.opensuse.org/conferences/oSC19/schedule#2019-05-25 the schedule is presented horizontally and requires scrolling to see the whole day. IMO that is counter intuitive. What's worse is that the talks below the arrow area can't be clicked as the arrow is layered above.

**Comment by hennevogel** [comment] 2019-03-26 10:56
Duplicate of #2434

**Closed by hennevogel** 2019-03-26 10:56 UTC

**Comment by Ana06** [comment] 2019-03-26 12:35
@lnussel there is an open discussion in https://github.com/openSUSE/osem/issues/2421 Feel free to participate with ideas of how to improve the design :wink:
