### ISSUE TITLE
Include all the speaker's name in every event while exporting

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1758] opened 2017-10-12 11:21 UTC
As any event can have multiple speakers so there should be the name of all the speakers in the exported files. As we have in following screenshot.

![screen shot 2017-10-12 at 4 50 09 pm](https://user-images.githubusercontent.com/20709985/31493596-839d70b8-af6d-11e7-9533-6f923440c2db.png)

**Comment by differentreality** [comment] 2017-10-12 13:16
@namangupta01 this is a duplicate of https://github.com/openSUSE/osem/issues/1743 where you commented before. Why did you also open this issue?

**Comment by namangupta01** [comment] 2017-10-12 13:18
Yup that was for email i guess!

**Comment by namangupta01** [comment] 2017-10-12 13:18
@differentreality Yup that was for email i guess!

**Comment by namangupta01** [comment] 2017-10-12 13:21
And also that was not dealing with multiple speakers i guess!

**Comment by differentreality** [comment] 2017-10-12 13:24
I realize it said email,  but we don't need a separate issue to include the names as well! 
Leave your comments on how to enhance that issue and its solution in the other PR please.

**Closed by differentreality** 2017-10-12 13:24 UTC
