### ISSUE TITLE
get rid of travel info

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2333] opened 2019-02-19 11:00 UTC
I wonder why we want the arrival and departure time of the attendees. In the registration:

![image](https://user-images.githubusercontent.com/16052290/53010314-ddc78280-343d-11e9-81f9-6ff7f699fbc2.png)

After registering:
![image](https://user-images.githubusercontent.com/16052290/53010559-8544b500-343e-11e9-8105-aea65fdb5fc4.png)

Should we get rid of this?

Related to https://github.com/openSUSE/osem/issues/2011

**Comment by Ana06** [comment] 2019-02-19 11:01
@differentreality @ddemaio any opinion?

**Comment by Ana06** [comment] 2019-02-19 12:14
@differentreality @ddemaio @bear454 @hennevogel  any opinion?

**Comment by bear454** [comment] 2019-02-19 15:55
I agree: https://gitlab.com/lfnw/osem/commit/d18cc02f0185df39bb4213d8a63a955dfb433dcb

**Comment by bear454** [comment] 2019-02-19 15:56
Want me to submit this as a PR, @Ana06 ?

**Comment by Ana06** [comment] 2019-02-19 16:27
@bear454 

> I agree: https://gitlab.com/lfnw/osem/commit/d18cc02f0185df39bb4213d8a63a955dfb433dcb
> Want me to submit this as a PR, @Ana06 ?

I would suggest we give the rest a bit of time to answer (just in case someone find it useful). If everybody agrees it would be great if you could send a PR :cupid:

**Comment by differentreality** [comment] 2019-03-07 04:55
This can now be part of surveys anyway.

Part of this, though, is migrating travel details of older conferences into surveys. 
We can make this a `good first issue` to handle the removal from the view file only. And let the DB fields be handled along with the above mentioned migration.

**Comment by Ana06** [comment] 2019-03-07 10:25
@differentreality 

> We can make this a good first issue to handle the removal from the view file only. And let the DB fields be handled along with the above mentioned migration.

well, you need two migrations, right? one data migration to move things around (if needed) and another migration to get rid of those fields. I think all this should be done together and I don't think it is a good candidate for good first issue. We have many small bugs lately anyway that we can label as good first issue.

**Comment by differentreality** [comment] 2019-03-07 17:05
Right, however, my point was not to split the migrations. I was merely saying we could drop the **view files** associated with questions, mainly because there are issues with questions, and organizers may or may not be able to see the answers to the questions anyway.
Touching tables, migrating data, that's another story.

**Comment by differentreality** [comment] 2019-04-29 18:44
Duplicate of https://github.com/openSUSE/osem/issues/1263

**Comment by Ana06** [comment] 2019-04-30 08:57
@bear454 it is clear we want to drop this (and since a lot of time ago seeing #1263). Can you please send that PR? :pray:

**Comment by bear454** [comment] 2019-10-07 21:47
> @bear454 it is clear we want to drop this (and since a lot of time ago seeing #1263). Can you please send that PR? pray

Sorry for the delay - I kept getting frustrated trying to rebase... finally got through. Tests already passed :heavy_check_mark: :smile:

**Comment by AndrewKvalheim** [comment] 2023-03-05 07:25
Completed in #2591

**Closed by AndrewKvalheim** 2023-03-05 07:25 UTC
Labels: need feedback :question:
