### ISSUE TITLE
Error opening revision history 

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1722] opened 2017-09-30 07:56 UTC
While opening revision history we are getting the error saying **Couldn't find organization**
1. When version.item_type == 'UserRoles' and role.name == 'organization_admin'
2. When version.item_type == 'Role' 
![screen shot 2017-09-30 at 12 34 07 pm](https://user-images.githubusercontent.com/20709985/31043918-7e949cca-a5e2-11e7-9308-5f78325edb04.png)

**Comment by differentreality** [comment] 2017-10-01 16:27
Duplicate of https://github.com/openSUSE/osem/issues/1725, isn't it @namangupta01 ?

**Comment by namangupta01** [comment] 2017-10-01 16:30
@differentreality I think it is somewhat related to this but its not exactly duplicate. Because in this issue we were trying to find the organization with conference_id and in #1725 we are passing wrong argument. Yes it seems somewhat related. Should i close that issue?

**Comment by differentreality** [comment] 2017-10-01 17:01
https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L227 too

**Comment by namangupta01** [comment] 2017-10-01 17:03
okay 👍

**Closed** 2017-10-20 20:01 UTC
Labels: Bug
