### ISSUE TITLE
edit speaker on talk

### ISSUE THREAD

**Issue by RobinEd** [openSUSE/osem#652] opened 2015-04-24 18:33 UTC
solution for https://github.com/openSUSE/osem/issues/651 doesn't work, so issue can't be closed. We need to be able to edit a talk and type in the speaker name. You can change the name when inputting the talk but not edit it afterwards, or even change their email address.

**Comment by differentreality** [comment] 2015-04-25 06:34
Duplicate of https://github.com/openSUSE/osem/issues/651
There is no solution as there is no bug, this is how the app works.
We, of course, consider all requests for new features, but you realize this is not something we can just code for you right now.

As Henne said the workflow of OSEM is the following:

User creates an account with OSEM -> User submits proposal
From the admin panel an admin can accept/reject the proposal.
An admin (from the admin panel) can also manage other aspects of the submitted proposals, such as the type of the proposal (talk or workshop) etc. The admin can manage proposal related stuff, but not user stuff. 
You, as an admin, should not be able to change a user's email!

Now for openSUSE instance, OSEM works with openSUSE accounts, that means that instead of creating one more account for OSEM, you use your openSUSE account to login to the app. 

I am not sure what's the actual problem at hand that you are facing but I hope that it makes more sense to you now, how the app works.

**Comment by hcderaad** [comment] 2015-04-25 12:31
@differentreality Thanks for explaining, but this doesn’t help us at all right now. Apparently we have to create separate (new) accounts for speakers and reregister talks, that's a lot of work for 1 small edit-field? Howcome this is so hard to implement? 
The actual problem is that all these seemingly small issues add up to a lot of time wasted in the organization of the conference. 
And ofcourse I sympathize with you as volunteers not having time to do everything, and I do appreciate the time your putting into helping us so far, but for us working with a tool that has so many limitations, bugs and missing features is at the very least a severe annoyance and prevents us from doing work we NEED to do on the conference itself, please understand that we are volunteers as well....

**Comment by ChrisBr** [comment] 2015-04-26 20:51
@hcderaad You don't understand, it's not just ''1 small edit-field''. The speaker name is not an attribute of a talk and it makes absolutely no sense to just stick a speaker attribute to the talk, there is a relation between the talk and the user model. And as @hennevogel and @differentreality already stated out OSEM uses the openSUSE authentication system, so you need an openSUSE account.
So this is nothing we can code quickie and you request this ONE week before the conference? The only thing which we possibly could implement is to change the user of the talk!

**Comment by hcderaad** [comment] 2015-04-27 06:35
@ChrisBr Changing the user of the talk would probably do the trick. I do fail to see how a Speaker is not an attribute to a talk (albeit a reference to another entity/table) because there IS a direct connection between talk and speaker. But perhaps we're mentioning the wrong field (speaker and submitter are the same value everywhere so for us there isnt much difference). 
From my point of view, you could also just add 2 extra fields to a talk (optional, a speaker name and a speaker bio), to use when the speaker is external (ie not a registered openSUSE user), but that's just a secondary idea.
We really do understand and appreciate the time you, Henne and Stella are spending on this, but please understand that we are also volunteers who are spending (a lot of) our own time on organizing the openSUSE 2015 conf and we're hitting issue after issue, which causes us to constantly having to workaround a system (while this isn't exactly the first conf we're organizing nor the first event organizing system we have work with), and that really causes a lot of frustration. 
So if it would be possible to have an option to change the user of the talk (and thereby changing the speaker), that would be extremely welcome.
Again, we really do appreciate your efforts on this.

**Comment by RobinEd** [comment] 2015-04-27 06:57
@ChrisBr we ask this "ONE week before the conference" because we have been trying to finalise the schedule for the past TWO weeks and have been running into issue after issue which we have had to resolve by copy pasting and typing stuff into spreadsheets. This has cost us stupid amounts of time, literally DAYS (and weeks if you figure we have had to reschedule to do the same thing again and again - oSC15 is NOT the only thing on our plate, you know!). We have several talks registered by us for other speakers and creating fake IDs, logging in with them, copy pasting the existing talks is yet more pointless time we have to spend on this. So now we have talks given by "Robin Edgar" or "Hans de Raad" which will not be given by us. The speakers can't find themselves in the schedules. We can't email the speakers through OSEM. There must be some way to do this which isn't time consuming and doesn't require people to ping pong issues as though there is no problem at all.

**Comment by differentreality** [comment] 2015-04-27 07:12
@RobinEd Hey, take it easy :) You are not the only one with other things on his plate, and we can't possibly know what is going on in other people's lives, so please let's be polite and careful not to offend people.

What @ChrisBr is saying is that you had access to OSEM for a long time and you could perhaps taken that opportunity to get to know it better before actually using it a few weeks prior to the conference, so that you could have compe up with suggested features much much sooner, so that neither us and nor (most importantly) you would be in such an anxiety state for no good reason. That would have given us a unique advantage to actually develop a couple of new features as well, as we are constantly improving OSEM :)

Indeed OSEM is build like this, everyone needs to submit their own proposals. I understand you haven't used OSEM before, which is why you did not know that. But that does not mean that OSEM is not doing its job, just that it does it in a different way than the one you would like. And that's OK, not everyone works the same way. I am not sure if we can properly address this feature request at this point.

There is indeed no reason why you would go into all that trouble to copy stuff in a spreadsheet. We did not have any problems with the past conferences we scheduled with OSEM - while it is agreed that the scheduling interface still needs a lot of love.
We are online on IRC literally all day long, for usage questions about OSEM, you can just ping us on opensuse-project or osem channels.

As far as any other issues are concerned, please try properly reporting them before making public exaggerating comments. We would appreciate it. Thank you.

**Comment by hcderaad** [comment] 2015-04-27 07:21
@differentreality Well, this is pretty much exactly why we've, in the last IRC meeting, suggested to the openSUSE board to evaluate some other systems than OSEM, because it may not exactly be fair to a very small team of volunteers (both on the development and the organizational side) to build a fully fledged event management system whilst organizing a conference.
We have been trying to work with OSEM for some months by now but have stonewalled by issue after issue. We really don't have the time to sort this all out, and I also don't think it's very fair to ask this from us. 
Again, if you can do anything about being able to change the speaker that would be great, for the other issues see the last IRC meetinglog: http://community.opensuse.org/meetings/opensuse-project/2015/opensuse-project.2015-04-26-09.00.html

**Comment by RobinEd** [comment] 2015-04-27 07:21
I will edit my profile to reflect above comments and redirect speakers to this page to explain why their talks are being given in my name.

**Comment by ChrisBr** [comment] 2015-04-27 08:33
For the record: the issues e, f, g, i and j are solved!

**Comment by bear454** [comment] 2016-03-15 16:47
I see @hcderaad's point here, maybe this is a better way to express it:

As the administrator of an event,
In order to assist my keynote speakers, or in order to migrate from another system,
I should be able to create registrants and events, and assign speakers to events.

Given a conference for which I am assigned the organizer's role,
When I am administering the event's registered users,
I should be able to add registered users.

Given a conference for which I am assigned the organizer's role,
When I am administering the events,
I should be able to add events.

Given an event I added as a conference organizer
when I edit the event,
I should be able to assign speakers.

**Comment by differentreality** [comment] 2017-04-14 13:30
Done in 790e2fd3a285fc765e681712754c23661619da27

**Closed by differentreality** 2017-04-14 13:30 UTC
