### ISSUE TITLE
Error downloading PDF if VENUE not set

### ISSUE THREAD

**Issue by sagarpreet-chadha** [openSUSE/osem#1726] opened 2017-10-01 18:55 UTC
<img width="1367" alt="screen shot 2017-10-01 at 8 34 25 pm" src="https://user-images.githubusercontent.com/14952645/31055921-fdf0c646-a6e7-11e7-9a1e-5d82c0690c78.png">

**Comment by rahul2240** [comment] 2017-10-02 06:09
Hi :smile: , #1683 this issue was already assigned to me and the pr #1688 is ready to merge.

**Comment by differentreality** [comment] 2017-10-02 06:20
@sagarpreet-chadha thank you for reporting this. As @rahul2240 said, we also have https://github.com/openSUSE/osem/issues/1683 for the same thing, and there is a PR that fixes it, which should be merged into our master soon.

Generally it is a good practice that you choose issues that have labels to avoid such problems. 

There are many other issues to choose from, if you want to work on something :)
You can get started with [junior issues](https://github.com/openSUSE/osem/labels/Junior)!

**Comment by differentreality** [comment] 2017-10-02 06:20
Closing as it is a duplicate of #1683

**Closed by differentreality** 2017-10-02 06:20 UTC
