### ISSUE TITLE
Name attribute in registration email not set 

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#818] opened 2016-03-04 08:09 UTC
The name attribute in registration email not set:

```
-----------------
Dear {name},

Thank you for Registering for oSC16.
-----------------
```

Could be related to #577, maybe we need to switch to :username as :name isn't mandatory anymore! Maybe we also need to check the other mail templates as well!

**Comment by Shriyanshagro** [comment] 2016-03-08 20:25
tried to solved the issue , check if it works
#https://github.com/Shriyanshagro/osem/commit/17e7f49100269d929e626701b502e9f3a11c35e1

**Comment by hennevogel** [comment] 2016-03-09 10:30
@Shriyanshagro  And who do you think sets @user? :-)

The variables are fetched in EmailSettings#get_values. There are no instance variables.

**Comment by Ana06** [comment] 2016-03-09 21:50
I think the problem is here (line 64 of email_settings.rb):

text = text.gsub "{#{key}}", value unless text.blank? || value.blank?

As it is said in issue #577,  name can be blank, and if that is the case {name} is not replaced. A possible solution could be having a function get_name() in User that returns the name if it is not blank. Otherwise it returns the username (or the email or the text 'user'). This function can be used in get_values (in email_settings.rb) to ensure that name is not blank.

**Comment by hennevogel** [comment] 2016-03-10 14:16
I would find it even cooler to just overload `#name`

**Comment by sonalkr132** [comment] 2016-03-26 14:16
This can be close since #865 is merged.

**Closed** 2016-04-04 14:34 UTC
Labels: Bug, Junior
