### ISSUE TITLE
Error on opening links to roles in revision history

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1750] opened 2017-10-08 19:11 UTC
When a role is assigned to a user, the link of that role is not working in revision_history.

![image](https://user-images.githubusercontent.com/26951824/31319962-0e4da3e0-ac8a-11e7-9c89-ad4b425bb578.png)

![image](https://user-images.githubusercontent.com/26951824/31319973-3b8b2346-ac8a-11e7-9034-ef6c4d783ff6.png)

**Comment by differentreality** [comment] 2017-10-17 12:51
@rishabhptr nice catch! 
When you prepare a PR for merging, make sure you add the issue (eg #1750) so that the issue is closed automatically, when the PR is merged :)

**Closed by differentreality** 2017-10-17 12:51 UTC
Labels: Bug
