### ISSUE TITLE
Fix Fixnum deprecated warnings

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1665] opened 2017-08-29 07:38 UTC
Fixnum is deprecated

**Comment by ViditChitkara** [comment] 2017-08-29 11:44
Can I take up this issue?

**Comment by faraazahmad** [comment] 2017-09-25 08:22
While running `bundle exec rspec --color --format documentation`, the Fixnum deprecated warnings appear to be due to the dependencies of of the required gems, rather than the business logic itself.

For example, the monetize gem
```
/home/faraaz/.rvm/gems/ruby-2.4.0/gems/monetize-1.4.0/lib/monetize.rb:87: warning: constant ::Fixnum is deprecated
```
similarly, it also occurs in the `formtastic` and `simplecov` gems. The issue should be created on repositories of those gems IMHO.

Please correct me if I'm wrong.
Thanks

**Comment by AEtherC0r3** [comment] 2017-09-28 07:38
For the upgrade to rails 5 #1714, I had to update formtastic, so the deprecation warnings that can be attributed to it have been fixed

**Comment by Ana06** [comment] 2017-11-23 08:46
@AEtherC0r3 but are there still deprecation warnings or do you mean that we can close this? 🤔

**Comment by Ana06** [comment] 2017-11-23 08:53
and Rails 5 PR is not still merged

**Comment by AEtherC0r3** [comment] 2017-11-23 14:09
@Ana06 I've only fixed the `formtastic` related deprecation warnings in #1714. The ones that are caused by `monetize`, `simplecov` or other gems, are still there.

**Comment by bear454** [comment] 2018-03-16 18:06
Resolved in https://github.com/openSUSE/osem/pull/1993

**Closed by bear454** 2018-03-16 18:06 UTC
Labels: Junior, good first issue
