### ISSUE TITLE
Blindvoting

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#981] opened 2016-05-02 08:54 UTC
We should introduce blind voting:

- You shouldn't be able to see the votes of the others
- You shouldn't be able to see the current mean
(- You shouldn't be able to see the author)

Otherwise your vote will be biased ...

**Comment by differentreality** [comment] 2016-05-02 09:25
Duplicate of #702 
And I would personally like to see this. I hope I will eventually find time to implement it.

**Comment by hennevogel** [comment] 2016-05-02 09:34
If it's a duplicate, close it :-)

**Closed by hennevogel** 2016-05-02 09:34 UTC
Labels: Feature
