### ISSUE TITLE
Pluralize conference and proposal controllers

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1120] opened 2016-08-04 10:14 UTC
The controller name should be in plural even for singular routes. For conference both `conference_controller.rb` and `admin/conference_controller.rb` should be changed.

http://alexander-clark.com/blog/rails-conventions-singular-or-plural
http://edgeguides.rubyonrails.org/routing.html#singular-resources

**Comment by differentreality** [comment] 2016-09-06 09:11
@richiethomas sure, you can go ahead! 
If you need any help you can ask here or you can find us on IRC (#osem at Freenode server) :)

**Comment by richiethomas** [comment] 2016-09-09 13:24
Hi @differentreality, just wanted to touch base on this issue.  I'm making good progress but I noticed that the two controllers mentioned touch a lot of different components in the code so I'll need more time to complete this.

**Comment by richiethomas** [comment] 2016-09-09 13:24
Just giving y'all a heads' up on my progress.

**Comment by richiethomas** [comment] 2016-09-17 22:19
Hi @differentreality I noticed this hasn't been assigned to me yet.  Is that something I can do, or does it need to be done by an admin?

Also, I have a pull request for this issue but the PR triggered a broken build.  Looks like the cause is due to an error installing PhantomJS in the build environment, so I'm not convinced that the breakage is related to my commits.  Let me know, thanks!

**Comment by differentreality** [comment] 2016-09-18 11:50
@richiethomas it is interesting that I can't assign you right now either. Not sure why. Either way that should not stop you, we have seen your PR and we know you are working on the issue. I will try the assignment later nonetheless.

As I mentioned on the PR, this particular failure on travis is indeed not a result from your PR. Sometimes that happens, and we need to restart travis. Thanks for the patience :-)

**Closed** 2016-10-03 20:28 UTC
Labels: Grooming, Junior
