### ISSUE TITLE
Not able to create event 

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#2376] opened 2019-02-27 19:21 UTC
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

After creating a conference, go to create events.
![bug](https://user-images.githubusercontent.com/25618739/53516677-dade2900-3af2-11e9-8f97-28c2ee309313.png)

**Expected correct behavior:**

Either redirect the user to /program/cfps to add cfp or allow the admin to create an event.

**Steps to reproduce:**

1.Create a conference
2.Create an event

**Comment by ehrenfeu** [comment] 2019-02-28 10:14
Duplicate of #2348 ?

**Comment by rahul2240** [comment] 2019-02-28 10:47
@ehrenfeu my bad.

**Closed** 2019-02-28 10:47 UTC
