### ISSUE TITLE
Unreachable code in ConferenceRegistrationsController#new

### ISSUE THREAD

**Issue by charliequinn** [openSUSE/osem#1140] opened 2016-08-11 23:36 UTC
Whilst writing specs in pull request #1138 I noticed that there are a couple of instances of unreachable code in ConferenceRegistrationsController new method.

**First instance** (check if current user and is registered) - https://github.com/openSUSE/osem/blob/master/app/controllers/conference_registrations_controller.rb#L22-L24

cannot be reached due to line 12 @conference.user_registered?(current_user)

**Second instance** (if OSEM_ICHAIN_ENABLED is true and user is guest) - https://github.com/openSUSE/osem/blob/master/app/controllers/conference_registrations_controller.rb#L16-L18

cannot be reached because of this guy https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L48 meaning that guest users won't have authorization to register if OSEM_ICHAIN_ENABLED = 'true' 

However, this causes a rather ambiguous error message to be displayed to the user ("Sorry, you can not register for #{conference.title}. Registration limit exceeded or the registration is not open. Maybe you need to sign in?"). 

I believe it makes sense to remove this from the ability model (provided it doesn't affect anything else) and keep it on the controller so that we can give the user a much more precise reason ("You must be signed in") as to why the user cannot register.

What do you think? Would greatly appreciate any feedback on the above.

**Comment by ChrisBr** [comment] 2016-08-17 06:25
I would confirm first instance, @differentreality can you also please have a look!

**Comment by ChrisBr** [comment] 2016-08-17 06:27
Second instance: I would prefer to have it in the ability.rb, however, you're right that the error message is misleading :( 
@differentreality what do you think?

**Comment by differentreality** [comment] 2016-08-17 06:32
The issue was also discussed in https://github.com/openSUSE/osem/issues/1054 but there hasn't been a proper solution.
I can confirm both instances mentioned. They definitely should be fixed.

ability.rb needs to represent all authorization rules we have. One of them is that a user which is not signed_in cannot access the new action of Registration. 
It is the controller that needs a bit of refactoring, removing what's not necessary, and putting things in the right order so that it makes sense to visitors.

**Comment by charliequinn** [comment] 2016-08-17 18:06
Yeah in hindsight I agree that keeping the authorization rules together (as opposed to dotted about controllers) is best practice.

I've written up a proposed set of 8 expected outcomes based on the 3 input parameters we currently have:

1. User signed in
1. OSEM_ICHAIN_ENABLED
1. registration period open && registration.new_record? && registration limit not exceeded

can be found here: https://docs.google.com/spreadsheets/d/1xVQ9vYQW4IvqOzVUett9rs7kifxKE8u1z3VKBTun-q0/edit

**Comment by differentreality** [comment] 2016-08-18 05:33
Yeap that looks like a plan!

**Closed** 2017-03-08 08:55 UTC
