### ISSUE TITLE
Admin booths#show gives error when no logo is present

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1916] opened 2017-12-23 08:30 UTC
**I'm submitting a ..**
- [x] Bug Report

admin booths#show gives error when there is no logo.
**Current behavior:**
![screenshot from 2017-12-23 12-47-59](https://user-images.githubusercontent.com/26951824/34317918-1099f446-e7e0-11e7-8b40-1d82ba8db5bf.png)

**Steps to reproduce:**
Add a new booth without a logo and click on the specific booth.

**Comment by differentreality** [comment] 2017-12-23 21:34
Duplicate of https://github.com/openSUSE/osem/issues/1909
Please make sure you check issues before opening one.

Also please prefer not to work on issues that are not confirmed by maintainers - that's very helpful for both you, and the reviewers. 
There are plenty of issues with a label to work on, why aren't you choosing one of those?

**Closed by differentreality** 2017-12-23 21:34 UTC

**Comment by rishabhptr** [comment] 2017-12-24 05:42
@differentreality Sorry, I didn't realise that #1909 was also for checking logos, I thought that we had similar check in user booths#show so it might have been missed therefore I made the pr.
