### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1879] opened 2017-12-11 18:39 UTC
There are several flaky tests : 
1. https://github.com/openSUSE/osem/blob/master/spec/features/lodgings_spec.rb#L8
![screen shot 2017-12-11 at 11 44 18 pm](https://user-images.githubusercontent.com/20709985/33847297-0e8e37f2-ded0-11e7-9c34-e8aa78fcf064.png)

2. https://github.com/openSUSE/osem/blob/master/spec/features/conference_registration_spec.rb#L31
@bear454 Please have a look!

**Comment by bear454** [comment] 2018-03-16 18:19
Duplicate of https://github.com/openSUSE/osem/issues/1803

**Closed by bear454** 2018-03-16 18:19 UTC
