### ISSUE TITLE
Unregistering from conference does not delete ticket purchase

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#821] opened 2016-03-04 14:11 UTC
Steps to reproduce:
* Make a conference and then tickets.
* Sign in with a different user, register to conference and  buy tickets
* Unregister form the conference 
* Sign in with admin and go to tickets area (url: http://localhost:3000/admin/conference/<conf>/tickets)
* You can still see tickets are there
* Sign in again with other user and register, now you have tickets you purchases last time you registered.

EDIT: Of course you can just use, rails c or pry instead.

**Comment by chashmeetsingh** [comment] 2016-03-05 14:52
@sonalkr132 can't reproduce

**Comment by sonalkr132** [comment] 2016-03-05 14:59
@chashmeetsingh get on #osem and hit me up. I will help you reproduce it.

**Comment by ChrisBr** [comment] 2016-03-07 12:22
I can reproduce. Yeah, if you unregister I'd expect that it deletes the ticket purchases ...

**Comment by rishabhs95** [comment] 2016-03-09 18:41
can i work on this issue?

**Comment by rishabhs95** [comment] 2016-03-09 21:44
worked on this issue according to its tests, sending the PR.

**Comment by rishabhs95** [comment] 2016-03-09 21:55
please review the PR #856

**Comment by differentreality** [comment] 2016-03-17 10:13
What are we expecting when we implement sales on tickets? 
User registers + pays for a ticket, the ticket cannot be unpaid, even if the user uregisters from the conference. Thus we keep ticket_purchase, since the ticket is already paid for? Inform organizers somehow about paid tickets from unregistered users?

**Comment by hennevogel** [comment] 2016-03-17 12:34
That is to be determined during the implementation I guess. Don't know the refund options of e.g. stripe

**Comment by hennevogel** [comment] 2016-04-04 14:34
Fixed in #876

**Closed by hennevogel** 2016-04-04 14:34 UTC
Labels: Bug, Junior
