### ISSUE TITLE
Add 😊 and get ISE 500

### ISSUE THREAD

**Issue by isbm** [openSUSE/osem#3363] opened 2024-04-14 14:12 UTC
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
In proposal description I copypasted "😊" symbol.

**Expected correct behavior:**
Obviously, to see it is in the text.

**Steps to reproduce:**
Write stuff and place "😊".

**Comment by hennevogel** [comment] 2024-04-15 10:11
Duplicate of #2686

**Closed by hennevogel** 2024-04-15 10:11 UTC
