### ISSUE TITLE
registration broken in master

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#622] opened 2015-04-01 12:14 UTC
Hi,

Looks like registration doesn't work anymore :(

This is when using the new one-page registration. I dunno how to get more error messages out of this...
![activity in owncloud1](https://cloud.githubusercontent.com/assets/551757/6940642/246b394a-d879-11e4-9ff3-b76aab2b8896.png)
![activity in owncloud1](https://cloud.githubusercontent.com/assets/551757/6940629/109d9714-d879-11e4-9421-da7fda3bdcdf.png)

Registering an existing user does not work either:
![activity in owncloud1](https://cloud.githubusercontent.com/assets/551757/6940670/5caf714a-d879-11e4-82dc-b59a0185b287.png)
"ActiveRecord::RecordNotFound (Couldn't find Conference without an ID):" from @danimo

**Comment by jospoortvliet** [comment] 2015-04-01 12:15
@hennevogel the one page thing might've broken something or is this something else? see https://conference.owncloud.org/conference/oCC2015/register as our instance

**Comment by danimo** [comment] 2015-04-01 12:16
Let's not confuse things: The error above is caused by the route 

`ActiveRecord::RecordNotFound (Couldn't find Conference without an ID):`

is caused by the route

https://conference.owncloud.org/admin/users

**Comment by differentreality** [comment] 2015-04-01 12:48
Can't recreate in my dev instance :/

Is this actually 3 different issues?
1) cannot register to a conference + create a user at the same time
2) cannot register an existing user
3) cannot access /admin/users page 

Is it possible that you provide more server logs please?

**Comment by differentreality** [comment] 2015-04-01 15:37
OK No 2 is due to the fact that the users do not have a username. 
Check if migration https://github.com/openSUSE/osem/blob/master/db/migrate/20141104131625_generate_username.rb is run

**Comment by differentreality** [comment] 2015-04-01 19:31
After chatting with @danimo on IRC, it seems that the migration that fills out the username field is not effective in his DB. 
He was using ruby version 2.0.0, he has updated to openSUSE 13.2 which ships with ruby version 2.1.3.
Rerunning the migration again did not help. Based on @danimo 's tries TempUser.all does not have any users (no loop happening).

**Comment by differentreality** [comment] 2015-04-03 08:35
1+2 are fixed.

/admin/users throws:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

**Comment by differentreality** [comment] 2015-04-07 08:02
https://github.com/openSUSE/osem/blob/master/db/migrate/20140730104658_migrate_roles_for_cancancan.rb#L13 seems to not have run properly leaving the DB without a resource

**Comment by jospoortvliet** [comment] 2015-04-07 14:03
Thanks for the feedback and help, @differentreality really appreciate it!

**Comment by ChrisBr** [comment] 2015-04-07 14:59
@jospoortvliet @differentreality Whats the status quo for now? Is there some work for us to do left?
I think the registration and email works now, don't they?

**Comment by differentreality** [comment] 2015-04-08 06:03
@ChrisBr No 3, no access to /admin/users (seems to be caused by inexistence of resource in role).
I haven't worked on it yet... Should do so today.

**Comment by ChrisBr** [comment] 2015-04-08 08:11
@differentreality Okay, if you need help let me know!

**Comment by differentreality** [comment] 2015-04-08 08:18
No 3 fixed with: 

Role.all.each do |role|
  unless role.resource
    role.resource = Conference.find_by(short_title: 'OCC14')
    role.save!
  end
end

**Comment by ChrisBr** [comment] 2015-04-08 08:25
@differentreality awesome! How can we protect that this happen again?

**Comment by differentreality** [comment] 2015-04-08 08:25
To sum up, we are not sure if registration issues were really bugs, as some of the migrations might not have been run in production environment (where the issue occured) and ruby -v was 
[01/04/2015-19:50:31] <danimo> ruby 2.0.0p247 (2013-06-27) [x86_64-linux]

Roles table seems to have had a bug due to the [migration] (https://github.com/openSUSE/osem/blob/master/db/migrate/20140730104658_migrate_roles_for_cancancan.rb#L10) not adding a resource.

**Closed by differentreality** 2015-04-08 08:25 UTC

**Comment by jospoortvliet** [comment] 2015-04-08 10:11
thanks for the debugging, folks! Great work, we just announced the ownCloud Contributor Conference 2015 - see how registration goes now.
