### ISSUE TITLE
[production][users#edit] NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#1003] opened 2016-05-19 07:58 UTC
users#edit threw this 3 times
<pre>
NoMethodError: undefined method `split&#39; for nil:NilClass
</pre>
[https://events.opensuse.org/users/12070/edit](https://events.opensuse.org/users/12070/edit)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/573d6a7e91219d000900000d)

**Comment by differentreality** [comment] 2016-05-19 08:16
Duplicate of https://github.com/openSUSE/osem/issues/995
I also cannot open the errbit link, not sure why.
And I have sent a PR https://github.com/openSUSE/osem/pull/999

**Closed by differentreality** 2016-05-19 08:16 UTC
Labels: Bug

**Comment by ChrisBr** [comment] 2016-05-19 08:19
Ah didn't see that, sorry! Thanks
