### ISSUE TITLE
Error in clean rake db:migrate

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#785] opened 2016-02-18 19:04 UTC
In a clean installation, when running rake db:migrate it throws the error:

```
  ActiveRecord::StatementInvalid: Mysql2::Error: Table 'opensouth.roles' doesn't exist: SELECT `roles`.* FROM `roles`
```
If also appears with sqlite:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: roles: SELECT "roles".* FROM "roles"
```

It seems a bug in rolify : https://github.com/RolifyCommunity/rolify/issues/241

Workaround:
 * the comment the line _rolify_ in _:app/models/user.rb_
 * run rake db:migrate
 * coment out the line  _rolify_ in _:app/models/user.rb_

**Comment by sonalkr132** [comment] 2016-02-19 02:31
hi @davidsf, Can you provide steps to recreate it? I did following:

```
rake db:drop
rake db:create
rake db:migrate
```

All I got was a warning message:
> [WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.

It doesn't seem to have any effect on working. ie I am able to assign roles to users and they persist.

**Comment by sonalkr132** [comment] 2016-02-19 02:48
I had looked into something related. We have following deprecation warning:

> /home/travis/build/openSUSE/osem/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/associations.rb:1694: warning: already initialized constant User::HABTM_Roles

That is most likely because we are defining rolify relation redundantly. [This comment](https://github.com/RolifyCommunity/rolify/issues/315#issuecomment-172129095) has some suggestion, however it didn't work in first try. Please look into it if you are working on it. I think it is closely related.

**Comment by davidsf** [comment] 2016-02-20 22:45
I'm trying to reproduce the bug, but now it's only show the warning that you say. 

Removing the line in user.rb:

  has_and_belongs_to_many :roles

the warning goes away.

**Comment by hennevogel** [comment] 2016-02-22 09:50
And then the tests still succeed?

**Comment by sonalkr132** [comment] 2016-02-22 09:58
@hennevogel `rake db:migrate` doesn't give error, it give warning message of:
> [WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.

It was fixed in https://github.com/RolifyCommunity/rolify/pull/356 and release with rolify 5.0.0 (we are using 3.4.0)

**Comment by hennevogel** [comment] 2016-02-22 10:01
Yes I'm interested if the warning goes away if we remove the `has_and_belongs_to_many`

**Comment by sonalkr132** [comment] 2016-02-22 10:05
I don't think having `has_and_belongs_to_many` is causing warning mentioned in the issue. I couldn't reproduce the error (I got the warning).
However, `has_and_belongs_to_many` is causing another warning message indeed:
> /home/travis/build/openSUSE/osem/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/associations.rb:1694: warning: already initialized constant User::HABTM_Roles

**Comment by differentreality** [comment] 2016-02-26 17:05
`has_and_belongs_to_many` relation in User is causing the following warning:

```
/home/differentreality/projects/osem/bundle/ruby/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/associations.rb:1694: warning: already initialized constant User::HABTM_Roles
/home/differentreality/projects/osem/bundle/ruby/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/associations.rb:1694: warning: previous definition of HABTM_Roles was here
```
The reason for that is that rolify is already creating that relationship between roles and users (https://github.com/openSUSE/osem/blob/master/app/models/user.rb#L8), however it uses the table users_roles (and not roles_users), which did not work very well with our implementation. So, @hennevogel, no if we remove that relationship there are parts of the code that will not work because we are not able to call `@role.users` anymore, as such **tests fail**.
Once we decide on https://github.com/openSUSE/osem/pull/700, I will keep rolify in User and remove the relationship, keeping table users_roles and re-writing some parts of the code accordingly.

As far as the other warning is concerned
`[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.`
I haven't seen that in a while I think. I cannot understand from the discussion if you are still seeing it or not. Either way when we decide on #700 I will also update the rolify to its newest version.

**Comment by differentreality** [comment] 2016-03-09 14:31
Can you confirm if this is solved?

**Comment by hennevogel** [comment] 2016-03-17 14:07
I guess we can close this...

**Closed by hennevogel** 2016-03-17 14:08 UTC
Labels: Bug, Grooming
